# Этап сборки
FROM python:3.9-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --user -r requirements.txt

# Финальный этап
FROM python:3.9-slim
WORKDIR /app
COPY --from=builder /root/.local /root/.local
COPY producer.py .
COPY nsl-kdd/ ./nsl-kdd/
ENV PATH=/root/.local/bin:$PATH
CMD ["python", "producer.py"]