# Этап сборки зависимостей
FROM python:3.9-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --user -r requirements.txt

# Финальный образ
FROM python:3.9-slim
WORKDIR /app
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
# Создаём папку models/
RUN mkdir -p /app/models
COPY train.py .
COPY nsl-kdd/ ./nsl-kdd/
CMD ["python", "train.py"]